# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'LBFirebaseChat' do
	pod 'Firebase', '~> 2.4.3'
 	pod 'JSQMessagesViewController'
end

target 'LBFirebaseChatTests' do

end

target 'LBFirebaseChatUITests' do

end

