# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'LBSwiftiOS7' do

pod 'Alamofire-SwiftyJSON'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Messaging'
pod 'JSQMessagesViewController'
pod 'AWSS3'
pod 'AWSCognito'
pod 'Alamofire', '~> 3.4.0'
pod 'AlamofireImage', '~> 2.4.0'

end

target 'LBSwiftiOS7Tests' do

end

target 'LBSwiftiOS7UITests' do

end

