# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LBLoadingAnimation' do
'NVActivityIndicatorView', :git => 'https://github.com/ninjaprox/NVActivityIndicatorView.git', :branch => 'swift2.3'
end

target 'LBLoadingAnimationTests' do

end

target 'LBLoadingAnimationUITests' do

end

